@extends('layouts.app')

@section('content')
    <div class="row display-flex mb-100">
        <div class="col-xl-12 col-sm-12 col-12">
            <div class="landing-content mb-0">
                <h2>Terms of Service</h2>
                <p>
                    Effective Date: 01/22/19<br />
                    <br />
                    Current version available at: https://CampusTeam.tv/legal/terms-of-service/<br />
                    <br />
                    We ask you to read carefully these Terms of Service (hereinafter &mdash; &ldquo;Terms&rdquo;) applicable to your use of the online services, defined below in Clause 2.1 hereof (hereinafter &mdash; &ldquo;Services&rdquo;) provided by &ldquo;VELOPAD Inc.&rdquo;, a company registered under the laws of the State of Delaware, United States of America (hereinafter &mdash; &ldquo;CampusTeam&rdquo;) at https://www.CampusTeam.tv website and other domains, specified below in Clause 2.1 hereof (hereinafter &mdash; &ldquo;Site&rdquo;). These Terms and any other policies available on this Site, referenced by or referencing to these Terms, shall jointly constitute, as added, amended, modified, supplemented or restated from time to time, binding agreement between you and CampusTeam applicable to your use of the Site and the Services (hereinafter &mdash; &ldquo;Agreement&rdquo;).<br />
                    For the avoidance of any doubts, this Agreement shall not be applicable to online services provided on any website other than the Services on the Site.<br />
                    1. Acceptance of Terms<br />
                    1.1. This Agreement shall enter into force as of the moment you first access the Site or commence use of any of the Services. By accessing, browsing or using the Site and/or any of the Services you irrevocably and unconditionally accept and adhere to these Terms and confirm that you agree to be bound by this Agreement without any exemptions, limitations and exclusions, and any and all provisions of this Agreement shall be enforceable to the fullest extent against you. If you access the Site or use any of the Services on behalf of a business (whether registered or operating without registration), that business hereby accepts the terms of this Agreement. It will hold harmless and indemnify CampusTeam, their officers, agents, employees and Partners from any claim, suit or action arising from or related to the use of the Site and Services or violation of the Agreement, including any liability or expense arising from claims, losses, damages, suits, judgments, litigation costs and attorneys&rsquo; fees.<br />
                    1.2. In the event you disagree with any provision hereof and would not like to be bound by this Agreement you shall cease use of the Site or the Services immediately.<br />
                    2. Description of Services and Additional Policies<br />
                    2.1. The Services provided by CampusTeam under this Agreement include web service available at: (i) https://campusteam.tv; (ii) https://collegeteam.tv; and (iii) https://sparta.games.<br />
                    2.2. In certain instances specific Services may be subjected to regulation of additional policies, terms or requirements (hereinafter &mdash; &ldquo;Additional Policies&rdquo;). In case of any discrepancies between Additional Policies and these Terms, Additional Policies shall prevail.<br />
                    2.3. CampusTeam may at its own discretion develop additional products, utilities and offerings or functionality of the Site or discontinue maintaining the Site and/or provision of any of the Services. In the event CampusTeam adds new products, utilities and offerings or makes additional functionality available through the Site this Agreement and, as the case may be, Additional Policies shall be fully applicable to such new products, utilities and offerings or additional functionality of the Site, unless otherwise provided by relevant Additional Policy.<br />
                    2.4. You confirm and acknowledge that you are of sufficient age to access this Site and use the Services in accordance with the laws of your country of residence or any other applicable legal requirements.<br />
                    3. Use of the Site and the Services<br />
                    3.1. You undertake to comply and adhere to provisions of this Agreement, Additional Policies, as well as any national and local laws and regulations applicable to your use of the Site and the Services.<br />
                    3.2. You undertake to use the Site and/or the Services in a manner consistent with their purpose and functionality within the user interface provided by CampusTeam. You shall not misuse the Site and/or the Services to cause any harm, damage, losses or interference for users, any third parties, CampusTeam, Company and their affiliates, partners, customers, suppliers and advertisers (hereinafter jointly &mdash; &ldquo;Partners&rdquo;), as well as operation of the Site and/or provision of the Services. In particular, under no circumstance you shall use the Site or the Services to:<br />
                    3.2.1. upload, download, post, transfer, send, transmit, distribute, email, link to or make available in any other way (hereinafter &mdash; &ldquo;Make Available&rdquo;) any images, photos, text, video, data, software, audio, sound, music, databases, links or other information (hereinafter &mdash; &ldquo;Content&rdquo;) that is illegal, harmful, slanderous, unethical, defamatory, harassing, threatening or infringing upon intellectual property rights, rights of privacy or publicity of third parties, CampusTeam, Company and/or Partners, incites hatred, bigotry, racial, ethnic, sexual, religious or social discrimination or is insulting to any persons, groups and/or entities;<br />
                    3.2.2. attempt to access the Site or the Services in a way other than through interface and instructions provided by CampusTeam;<br />
                    3.2.3. impersonate any person, representative of a legal entity and/or any organisation without authorization, including employees of CampusTeam, Company and/or Partners, forum moderators, website owners and misrepresent the source of any information;<br />
                    3.2.4. harm or exploit minors in any way or collect their personal information;<br />
                    3.2.5. Make Available unsolicited advertising information, spam, junk mail, pyramid schemes, multilevel marketing (MLM), Internet earning systems and email businesses, chain letters, as well as use the Site or the Services for participation in any of the above;<br />
                    3.2.6. Make Available any materials containing viruses, Trojan horses, worms, bots or other code, files or programs designed to interfere, hinder or impair the operation of any computer, telecommunication equipment or software;<br />
                    3.2.7. Make Available any Content which is false, misleading and/or promoting illegal activities;<br />
                    3.2.8. collect and store personal data, private and personally identifiable information without express consent and authorization of the holder;<br />
                    3.2.9. Make Available Content in violation of any other provisions hereof or applicable laws and regulations; and<br />
                    3.2.10. assist to any person to perform any of actions referenced to in Sub-clauses 3.2.1-3.2.9.<br />
                    4. User Account<br />
                    4.1. You may be provided with an account by Company for the purpose of improving your experience at the Site and use of the Services, as well as obtain access to specific additional other products, utilities and offerings provided by CampusTeam.<br />
                    4.2. In order to obtain a user account you are required to complete the registration process. You hereby represent and warrant that any and all information submitted to CampusTeam in the course of the registration is accurate and true. You undertake to keep your registration information up to date.<br />
                    4.3. Upon completion of the registration process you will obtain a password and designation of an account. You are responsible for keeping your password in secrecy and you acknowledge and agree that you are responsible for any actions performed under your account, unless you immediately informed Company of any unauthorised use of your password and/or account. You shall log off each time at the end of the session and CampusTeam and/or Partners shall bear no liability for any harm, loss or damage resulting from your failure to comply with requirements of this Clause 4.3.<br />
                    4.4. You acknowledge and agree that CampusTeam shall be entitled to terminate or suspend your account at its sole discretion without any notice to you in the event of your breach of this Agreement, Additional Policies or without any reason. You understand that termination of your account may lead to blocking, deletion and limitation of your access to Content, information and files uploaded, shared, submitted and made available in association with your account, as well as access to some of the products, utilities and offerings of CampusTeam or Partners (as the case may be).<br />
                    4.5. You hereby acknowledge and agree that the account assigned to you under this Section 4 is provided to you by CampusTeam under separate terms of service which shall be separately accepted by you in order to complete the registration process. In the event of any discrepancies between provisions of this Section 4 and any such terms of service of CampusTeam the latter shall prevail.<br />
                    5. Intellectual Property Rights<br />
                    5.1. You hereby expressly and irrevocably acknowledge and agree that accessing the Site and using the Services does not vest you with any right, title or interest in intellectual property and other rights to Content which is accessible at the Site or through the Services owned or licensed by CampusTeam, Partners or any third parties. You undertake not to use, sell, distribute, resell, decompile, disassemble, attempt to discover any source code, reverse engineer, modify, rework, reproduce, display, publicly perform, broadcast, rent, create security interest in, pledge, lien, encumber, license, make derivative works from Content accessible at the Site or through the Services owned or licensed by CampusTeam, Partners or any third party. No right of ownership or license, whether express, implied or any other, is granted to you to Content of CampusTeam, Partners or any third party, any portion of the Site and/or the Services, except as expressly provided in Clause 5.2 hereof or in Additional Policies.<br />
                    5.2. In order to use the Site and the Services you are granted personal, non-exclusive, worldwide, limited, non-assignable, non-transferrable, royalty free, revocable license to access, review, reproduce, cache, print, distribute and store Content retrieved from the Site or Services owned by CampusTeam only within the functionality of the interface of the Site or the Services through common consumer web browser, provided that you strictly comply with limitations contained herein. Unless expressly permitted by CampusTeam, no commercial use of Content, the Site or the Services is allowed.<br />
                    5.3. You hereby acknowledge and agree that, to the extent permitted by the applicable law, CampusTeam, Partners and any of their users are granted with non-exclusive, non-transferrable, irrevocable, royalty-free, worldwide license to use Content and information submitted by you to the Site or through the Services for the purposes of operation of the Site, the Services or other products, utilities and offerings of CampusTeam or Partners, including the queries submitted in the search box of the search engine available at the Site or through the Services, provided that you are the person vesting in intellectual property rights to such Content and information.<br />
                    6. Third-Party Content and Copyright Infringement<br />
                    6.1. CampusTeam does not exercise control over any of the third parties&rsquo; content and resources, you hereby acknowledge and agree that CampusTeam is not responsible for accessibility, safety, accuracy, availability, legality or completeness of information, Content, advertising, commercial offers, products, services and materials on the third party websites and resources or published by third party on the Site. CampusTeam does not monitor, endorse, review, consider or verify the information and/or Content specified in this Clause 6.1 and is not responsible for any harm, losses and damages, direct or indirect, arising out of your use, accessing, reliance on, purchase, downloading or dealing with any such third party Content published on the Site or on third party websites and resources.<br />
                    6.2. It is the policy of CampusTeam to respond to notices of alleged copyright infringement sent in compliance with applicable legal requirements. For CampusTeam products and services which have account holders, CampusTeam may, at its sole discretion and in appropriate circumstances, terminate the accounts of repeat infringers.<br />
                    If you would like to submit a notice of an alleged copyright infringement, please fill in the online form and follow the guidelines available at https://campusteam.tv/support/copyright-complaint/.<br />
                    If you believe that a notice of an alleged copyright infringement identifying your Content was filed in error, please submit a counter-notice at https://campusteam.tv/support/reinstate-links/counter-notice/.<br />
                    If you have removed Content defined in the notice of claimed copyright infringement and would like to reinstate the link that has been removed from the search results, please fill in the online form and follow the guidelines available at https://campusteam.tv/support/reinstate-links/removed/.<br />
                    We strongly encourage you to submit your notices of alleged copyright infringement, counter-notices and reinstatement requests via the online forms referred to above. Use of these forms will ensure a more expedient reply to your valid and complete notices, counter-notices and reinstatement requests. However, CampusTeam still accepts notices, counter-notices and reinstatement requests submitted by other means. By submitting any such notices, counter-notices and reinstatement requests via any other means of communication (such as email, fax or postal mail), you hereby acknowledge and agree that CampusTeam&rsquo;s processing of same may be substantially delayed and less effective, and your further hereby consent without any objection to such slower processing speed and decreased effectiveness.<br />
                    If you would nevertheless prefer to use other means of communication, please send any written communication to CampusTeam&rsquo;s designated agent at the address provided below (no email attachments, please). CampusTeam cannot guarantee that emails with attachments will be received for safety and security reasons. Therefore, your email containing attachments will likely be not processed.<br />
                    If you are sending a notice of alleged copyright infringement using other means of communication (such as email, fax or postal mail), please provide the information required, keeping the order of presentation. In particular, you are required to provide at least the following information:<br />
                    (1)Your first name and last name;<br />
                    (2) Your address (including the country of residence / location) and telephone number;<br />
                    (3) Your email address (if available);<br />
                    (4) Name, address and contact details of the copyright holder you represent or indication that you act in your own name;<br />
                    (5) Type, identification and description of the copyrighted work claimed to have been infringed;<br />
                    (6) Precise location (URL) of the authorised copy of the work (for example, if the authorised copy is available on the copyright holder&rsquo;s website) or specify that the work is not available online;<br />
                    (7) Identification of the material that is claimed to be infringing and nature of the infringement;<br />
                    (8) Precise location (URL) of the material that is claimed to be infringing;<br />
                    (9)The following statements:<br />
                    a. &ldquo;By submitting the notice and signing with my signature, I confirm that I have a good faith belief that the use of the material in the manner complained of is not authorised by the copyright owner, its agent, or the law&rdquo;; and<br />
                    b. &ldquo;I confirm that the information in this notification is accurate, and under penalty of perjury, that I am authorized to act on behalf of the owner of an exclusive right that is allegedly infringed&rdquo;;<br />
                    (10) Your signature and date of the notice.<br />
                    Please note that submission of false claims or provision of false information may lead to legal liability.<br />
                    7. Privacy Policy<br />
                    7.1. You hereby acknowledge and agree that in order to ensure proper functionality of the Site and provision of the Services, as well as other products, utilities and offerings, CampusTeam and Partners are entitled to collect, store, process and transmit certain information related to your use of the Site and the Services. Please note that our Privacy Policy applies to such matters. The Privacy Policy is located at: https://campusteam.tv/legal/privacy/.<br />
                    7.2. You hereby acknowledge and agree that through the use of the Site or the Services you provide your express and unconditional consent for the collection and use of the information under Clause 7.1 hereof, including disclosure of the information: (i) at the legitimate requests of relevant authorities in compliance with applicable law; (ii) for protection of rights, interests and property of CampusTeam, Company, Partners, holders of exclusive rights and users; (iii) in the event of sale of the Site or the Services, acquiring of CampusTeam by third party or in other similar cases; (iv) in other instances as provided by Privacy Policy.<br />
                    8. No Warranty and Limitation of Liability<br />
                    8.1. You hereby acknowledge and agree that, although CampusTeam employs commercially reasonable efforts to provide the best possible user experience, Content, the Site and the Services are provided to you on &ldquo;as is&rdquo;, &ldquo;as available&rdquo; and &ldquo;with all faults&rdquo; basis and you use Content, the Site and the Services exclusively at your own risk without any express or implied representations and/or warranties of any kind by CampusTeam and/or Partners including, but not limited to, as follows: (i) warranties of suitability for particular purpose, non-infringement, title and merchantability; (ii) representations and warranties that Content, the Site or the Services will meet your requirements and are error-free, accurate, ensure uninterrupted service, secure, reliable, useful, available, meeting certain quality standards or your needs or that any errors occurring in Content, on the Site or in the Services will be corrected.<br />
                    8.2. You hereby acknowledge and agree that Content, the Site and the Services are provided for information purposes only and CampusTeam does not accept any liability related to your reliance on or consequences of your following any information, including professional advice, whether legal, financial, medical or otherwise. Any Content or other material obtained from the Site or through the Services is used exclusively at your discretion and risk and you shall be solely responsible for any loss, damages or harm to computer systems, hardware or data that result from use of such Content or other material.<br />
                    8.3. You hereby acknowledge and agree that liability of CampusTeam and Partners hereunder is limited and, to the extent permitted by applicable law, CampusTeam, Partners and their distributors, officers, employees, agents, partners and licensors shall bear no liability for direct, indirect, incidental, special, consequential exemplary or punitive damages, any loss of profit, revenues or data, loss of goodwill, cost of substitute services, based on any theory of liability, resulting from: (i) your use of the Site or the Services; (ii) reliance on Content or any information available at the Site or through the Services; (iii) actions undertaken under your account, including, but not limited to, in the event of unauthorised access to your account, data or Content; (iv) any other matter associated with Content, the Site or the Services. In all cases CampusTeam and Partners are not liable for any loss or damage that is not reasonably foreseeable.<br />
                    8.4. In the event law of specific jurisdiction applicable to limitation or exclusion of liability of CampusTeam and Partners and their distributors, officers, employees, agents, partners and licensors under this Section 8 does not permit certain types of exclusion of warranties or liability, to the extent permitted by applicable law, total liability of CampusTeam and Partners and their distributors, officers, employees, agents, partners and licensors under any grounds shall be limited to the amounts paid by you for Content, access to the Site or use of the Services or, at the discretion of CampusTeam and/or Partners, your exclusive remedy shall be provision of the Services to you again.<br />
                    9. Modification, Limitation and Termination of the Site and the Services<br />
                    9.1. You hereby acknowledge and agree that CampusTeam shall be entitled to add, alter, modify, as well as suspend, stop, discontinue, cease maintenance, updating and correction of errors with respect to any functionality of the Site and/or the Services, including, but not limited to, to terminate the Site or any of the Services without any notice to you.<br />
                    9.2. You hereby acknowledge and agree that CampusTeam at its own discretion shall be entitled to impose limitations and restrictions on your use of the Site and/or the Services. The limitations and restrictions may be established for certain categories of users, including, but not limited to, depending on location, language, age, availability of rights to Content, legal requirements or other reasons, and may include unavailability of specific functionality of or the overall access to Content, the Site and/or the Service, limitations for storage of Content under your account and otherwise.<br />
                    9.3. You hereby acknowledge and agree that in addition to rights of Company under Clause 4.4 hereof, CampusTeam shall be entitled to suspend and terminate your access to the Site or the Services at its sole discretion without any notice to you.<br />
                    10. Miscellaneous Provisions<br />
                    10.1. This Agreement, including Additional Policies, as the case may be, constitutes the entire agreement between you and CampusTeam and supersedes any prior versions of the Agreement, Terms, as well as arrangements, correspondence, membership conditions and any other similar terms and conditions. This Agreement is applicable exclusively to relations between you and CampusTeam and does not create any third-party beneficiary rights.<br />
                    10.2. CampusTeam shall be entitled to modify and amend this Agreement, Terms and any of the Additional Policies at its sole discretion without any prior notice to you. These modifications and amendments may be due to the changes on the Site, in the Services or in order to ensure compliance with legal requirements or for any other reasons. The modifications and amendments will become effective as of the moment they are available on this page, unless otherwise expressly specified therein.<br />
                    10.3. The failure of CampusTeam to exercise or enforce any of its rights hereunder shall not be considered as waiver of such rights. In the event any provision of the Agreement is found to be invalid or unenforceable by the competent court or state body, the parties hereto acknowledge and agree that other provisions of the Agreement remain in full force and effect. The parties undertake to make every effort necessary to replace such invalid and unenforceable provision with the valid and enforceable provision that reflects intentions of the Parties to the maximum extent possible.<br />
                    10.4. CampusTeam shall be entitled to assign, transfer, pledge or otherwise alienate its rights hereunder, in whole or in part, at any time at CampusTeam&rsquo;s own discretion without any notice to you. You hereby acknowledge and agree that you are not entitled to transfer any rights or obligations hereunder, including, but not limited to, any rights associated with your account related to Content, the Site or the Services.<br />
                    10.5. You and CampusTeam hereby acknowledge and agree that this Agreement shall be construed and governed in accordance with laws of State of Delaware, United States of America without giving regard to its conflict of laws rules. Any claim, controversy or dispute arising out of or in relation of this Agreement or Additional Policies shall be exclusively referred for resolution to the state courts of State of Delaware. To the extent permitted by applicable law, you hereby expressly and irrevocably agree to submit to the jurisdiction of the state courts of State of Delaware with respect to any claim, controversy or dispute arising out or in relation of this Agreement.<br />
                    <br />
                </p>
            </div>
        </div>
    </div>
@endsection